{
  "formatVersion": "1.1",
  "component": {
    "url": "../../miuix-core/0.9.3/miuix-core-0.9.3.module",
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix-core",
    "version": "0.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-core.aar",
          "url": "miuix-core-android-0.9.3.aar",
          "size": 13033,
          "sha512": "67c881abe8047b0f16fec37c06c742f75e8bd7b0675a3e3dd114716204465289c182c3857048273d5d5139d5aa91f5c14a04a0c70da698d3a12a8107e933848e",
          "sha256": "c5a7bc50ace527afb9c56fe5f4ba5c5d99c8c06fe88486caa2f471f50c1256b6",
          "sha1": "cf74bb5b9ec5bd30664a719a92e47ff82fe98901",
          "md5": "399f0834736b3c27401f4cc04e99c2e8"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-core.aar",
          "url": "miuix-core-android-0.9.3.aar",
          "size": 13033,
          "sha512": "67c881abe8047b0f16fec37c06c742f75e8bd7b0675a3e3dd114716204465289c182c3857048273d5d5139d5aa91f5c14a04a0c70da698d3a12a8107e933848e",
          "sha256": "c5a7bc50ace527afb9c56fe5f4ba5c5d99c8c06fe88486caa2f471f50c1256b6",
          "sha1": "cf74bb5b9ec5bd30664a719a92e47ff82fe98901",
          "md5": "399f0834736b3c27401f4cc04e99c2e8"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "miuix-core-android-0.9.3-sources.jar",
          "url": "miuix-core-android-0.9.3-sources.jar",
          "size": 4282,
          "sha512": "b3f949dec81cc301e97bcf76ee8988d77473a27fb5190716eb2cb9c09eeb4f36bf9a3eeb184219b4346de728ac68c6d353b6f25737c6cbcb151c4b43f31968ba",
          "sha256": "b229381fa0cce5e3f834f81bb1b72f42a8ed2c1d4d4786e9f177d6778b0a9503",
          "sha1": "7529ffd262fb70724e5f002a72cefc5ec81ec79e",
          "md5": "a229ab131038d17deb12d0288d5b00ac"
        }
      ]
    }
  ]
}
