{
  "formatVersion": "1.1",
  "component": {
    "group": "top.yukonga.miuix.kmp",
    "module": "miuix-squircle",
    "version": "0.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "top.yukonga.miuix.kmp",
          "module": "miuix-shader",
          "version": {
            "requires": "0.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "miuix-squircle-metadata-0.9.3.jar",
          "url": "miuix-squircle-0.9.3.jar",
          "size": 8760,
          "sha512": "407477e61f3ae88030a51cfe741cadb993a2c30b308d50fdd60b8b724a65cf58761771684642214f45273f4e2b6fca99da962570afb3b193118a6c6238df9625",
          "sha256": "9c83650a6be9d92ffb07a7469c6199249475c6c261714ab22975ef783018783d",
          "sha1": "3da2233d9f73cdb4643a80fd89a90de42675f5e8",
          "md5": "e4e80ee08f5feecb39b54227255da559"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "miuix-squircle-kotlin-0.9.3-sources.jar",
          "url": "miuix-squircle-0.9.3-sources.jar",
          "size": 37921,
          "sha512": "f7d71b62cef0287e1c68a4f85b347a786aff4660331e1eb910974b47b54551790a85ec221a1a6e302211c7aaea8fa85baf61dc89ff2e8cc0439d089d7853fa22",
          "sha256": "bd7cf0ebef97c97b1e95f6b15f043f678645d19cd2e03a43a3d2edfdffd1d74b",
          "sha1": "dd7db1a105b0a3c98ca4600e5f5d470cd9f4dd85",
          "md5": "7e7e2366088a3082bbca1038601d3656"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../miuix-squircle-android/0.9.3/miuix-squircle-android-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-android",
        "version": "0.9.3"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../miuix-squircle-android/0.9.3/miuix-squircle-android-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-android",
        "version": "0.9.3"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../miuix-squircle-android/0.9.3/miuix-squircle-android-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-android",
        "version": "0.9.3"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../miuix-squircle-desktop/0.9.3/miuix-squircle-desktop-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-desktop",
        "version": "0.9.3"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../miuix-squircle-desktop/0.9.3/miuix-squircle-desktop-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-desktop",
        "version": "0.9.3"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../miuix-squircle-desktop/0.9.3/miuix-squircle-desktop-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-desktop",
        "version": "0.9.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-iosarm64/0.9.3/miuix-squircle-iosarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-iosarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-iosarm64/0.9.3/miuix-squircle-iosarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-iosarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-iosarm64/0.9.3/miuix-squircle-iosarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-iosarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-iosarm64/0.9.3/miuix-squircle-iosarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-iosarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-iossimulatorarm64/0.9.3/miuix-squircle-iossimulatorarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-iossimulatorarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-iossimulatorarm64/0.9.3/miuix-squircle-iossimulatorarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-iossimulatorarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-iossimulatorarm64/0.9.3/miuix-squircle-iossimulatorarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-iossimulatorarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-iossimulatorarm64/0.9.3/miuix-squircle-iossimulatorarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-iossimulatorarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../miuix-squircle-js/0.9.3/miuix-squircle-js-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-js",
        "version": "0.9.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../miuix-squircle-js/0.9.3/miuix-squircle-js-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-js",
        "version": "0.9.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../miuix-squircle-js/0.9.3/miuix-squircle-js-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-js",
        "version": "0.9.3"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../miuix-squircle-js/0.9.3/miuix-squircle-js-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-js",
        "version": "0.9.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-macosarm64/0.9.3/miuix-squircle-macosarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-macosarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-macosarm64/0.9.3/miuix-squircle-macosarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-macosarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-macosarm64/0.9.3/miuix-squircle-macosarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-macosarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../miuix-squircle-macosarm64/0.9.3/miuix-squircle-macosarm64-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-macosarm64",
        "version": "0.9.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../miuix-squircle-wasm-js/0.9.3/miuix-squircle-wasm-js-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-wasm-js",
        "version": "0.9.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../miuix-squircle-wasm-js/0.9.3/miuix-squircle-wasm-js-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-wasm-js",
        "version": "0.9.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../miuix-squircle-wasm-js/0.9.3/miuix-squircle-wasm-js-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-wasm-js",
        "version": "0.9.3"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../miuix-squircle-wasm-js/0.9.3/miuix-squircle-wasm-js-0.9.3.module",
        "group": "top.yukonga.miuix.kmp",
        "module": "miuix-squircle-wasm-js",
        "version": "0.9.3"
      }
    }
  ]
}
